# Generated by Django 3.2.16 on 2023-05-26 12:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Uploader',
            fields=[
                ('username', models.CharField(db_index=True, max_length=30, unique=True)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_token', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Audio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='record/')),
                ('audio_token', models.CharField(default=uuid.uuid4, editable=False, max_length=50, unique=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audios', to='record.uploader')),
                ('user_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='record.uploader')),
            ],
        ),
    ]
