# Generated by Django 3.2.16 on 2023-05-27 08:36

from django.db import migrations, models
import record.validators


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_remove_audio_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio_file',
            field=models.FileField(upload_to='', validators=[record.validators.validate_file_extension]),
        ),
    ]
