version: '2.12.2'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - db-data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
     - ./.env
  web:
    build: .
    restart: always
    volumes:
      - media_value:/app/media/
    ports:
      - 8000:8000
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  db-data:
  media_value: